excludes:
    scopes:
        - pattern: ".*"
          reason: "DEV_DEPENDENCY_OF"
          comment: "Exclude all development dependencies, including test tools."
    paths:
        - pattern: "^python/tests/.*"
          reason: "TEST_TOOL_OF"
          comment: "Files in the python/tests directory are excluded as they are used for testing purposes."
    packages:
        - id: "PyPI::pytest-metadata:3.1.1"
          reason: "TEST_TOOL_OF"
          comment: "Exclude pytest-metadata as it is only used for testing."
