excludes:
    scopes:
        - pattern: "build-dependencies"
          reason: "BUILD_DEPENDENCY_OF"
          comment: "Packages for building the code only."
        - pattern: ".*"
          reason: "DEV_DEPENDENCY_OF"
          comment: "Exclude all development dependencies, including test tools."
    paths:
        - pattern: ".*"
          reason: "TEST_TOOL_OF"
          comment: "Files in the python/tests directory are excluded as they are used for testing purposes."
