excludes:
    scopes:
        - pattern: "build-dependencies"
          reason: "BUILD_DEPENDENCY_OF"
          comment: "Packages for building the code only."
        - pattern: "dev-dependencies"
          reason: "DEV_DEPENDENCY_OF"
          comment: "Packages for development only."
        - pattern: "tests.*"
          reason: "TEST_TOOL_OF"
          comment: "This directory contains tests which are not distributed."
    paths:
        - pattern: ".*"
          reason: "BUILD_TOOL_OF"
          comment: "invisible"
